theme: jekyll-theme-minimal
title: "The Athenas"
description: "A peer network for women leaving academia"
sidebar: "The Post Academic Athenas Slack Channel is dedicated to providing a safe peer support experience for female-identified and non binary people to share wisdom and to talk about alternatives to a traditional academic job. 

Interested in joining us? Send an email to postacathenas@gmail.com"
